syntax = "proto3";

package Flipper_One_Rpc;

import "input.proto";
import "frame.proto";

message RpcMessage {
    oneof content {
        Flipper_One_Frame.Frame frame = 1;
        Flipper_One_Input.ButtonEvent button_event = 2;
        Flipper_One_Input.TouchEvent touch_event = 3;
        StartVirtualDisplayRequest start_virtual_display_request = 4;
        StopVirtualDisplayRequest stop_virtual_display_request = 5;
        RpcSessionCloseRequest rpc_session_close_request = 6;
    }
}

message StartVirtualDisplayRequest {
}

message StopVirtualDisplayRequest {
}

message RpcSessionCloseRequest {
}
